---
title: "P1-Kang"
subtitle: Function for computing analytic standard error (the delta method) of linear equating using random group desing
author: Chansuk Kang
---

# Data prep
```{r, eval=FALSE}
setwd("C:/Users/Chansuk/Desktop/edps845/edps-845/assignments")
data("ACTmath")
library("equate")
```

# Frequency tables of random group equating
```{r, eval=FALSE}
x <- as.freqtab(ACTmath[, 1:2])
y <- as.freqtab(ACTmath[, c(1, 3)])
```

# Function
```{r, eval=FALSE}
lin_rg <- function (x, y, ...){

     xscale <- scales(x)

  #use stats to get linear equating (revised from equate::linear)
      sigmax <- sd.freqtab(x)
      sigmay <- sd.freqtab(y)
      mux <- mean(x)
      muy <- mean(y)
      slope <- sigmay/sigmax
      intercept <- muy - slope*mux

    lyx <- intercept + slope*xscale
   
  # get se
    sigmaysq <-var.freqtab(y)
    sux <- summary(x)
    nx <- sux$n
    suy <- summary(y)
    ny <- suy$n
    skx <- skew.freqtab(x)
    sky <- skew.freqtab(y)
    kux <- kurt.freqtab(x)
    kuy <- kurt.freqtab(y)
    
    sk <- (skx/nx + sky/ny)
    zs <- (xscale - mux)/sigmax
    ku <- (kux -1)/4*nx + (kuy - 1)/4*ny
    
    lse <- sigmaysq * (1/nx + 1/ny + sk * zs
          + ku * zs ^ 2)
    # if x and y are assumed normally distributed
    lse1 <- (sigmaysq/2) * (1/nx + 1/ny) * (2 + zs ^ 2)
    # if sample size for x and y are assumed to be equal
    lse2 <- ((2*sigmaysq)/(nx + ny)) * (2 + zs ^ 2)
    
  out <- cbind(lyx, lse, lse1, lse2)
  return(out)
}
```

# Comparison to bootstrap standard error (from equate::equate)
```{r, eval=FALSE}
eql <- equate(x, y, type = "l", method = "none", boot = T, reps = 100)
#bootstrap standard error
eql$boot$se
round(eql$boot$se, 2)
round(mean(eql$boot$se), 2)
```

